In [1]:
import numpy as np

In [2]:
x_trn = np.array([[24000, 8],
                  [30000, 2],
                  [35000, 7],
                  [34500, 1],])

x_tst = np.array([[34000, 1],
                  [12000, 1]])

####Standard Scaling

In [6]:

col1 = x_trn[:,0]
trf_col1 = (col1 - col1.mean())/np.std(col1)
print(np.mean(trf_col1),np.std(trf_col1))

col2 = x_trn[:,1]
trf_col2 = (col2 - col2.mean())/np.std(col2)
print(np.mean(trf_col2),np.std(trf_col2))

0.0 1.0
0.0 1.0


###All columns at once

In [4]:
means = x_trn.mean(axis=0)
stds = x_trn.std(axis=0)
print((x_trn-means)/stds)

[[-1.55501304  1.15079291]
 [-0.19791075 -0.82199494]
 [ 0.93300782  0.82199494]
 [ 0.81991597 -1.15079291]]


for test data

In [7]:
print((x_tst-means)/stds)

[[ 0.70682411 -1.15079291]
 [-4.26921761 -1.15079291]]


In [9]:
from sklearn.discriminant_analysis import StandardScaler


scaler = StandardScaler()
print(scaler.fit_transform(x_trn))
print(scaler.transform(x_tst))
print(scaler.mean_)
print(scaler.scale_)

[[-1.55501304  1.15079291]
 [-0.19791075 -0.82199494]
 [ 0.93300782  0.82199494]
 [ 0.81991597 -1.15079291]]
[[ 0.70682411 -1.15079291]
 [-4.26921761 -1.15079291]]
[3.0875e+04 4.5000e+00]
[4.42118480e+03 3.04138127e+00]
