In [2]:
import numpy as np
from sklearn.impute import KNNImputer

In [3]:
X = np.array([[1, 2, np.nan],
              [8, 6.3, 5.6],
              [1.2, 2.3, 4],
              [1.25, 2.35, 5],
              [1.2, 2.4, 3],
              [np.nan, 6, 5],
              [10, 6.43, 5.61]])

In [4]:
imputer = KNNImputer(n_neighbors=1)
imputer.fit_transform(X)

array([[ 1.  ,  2.  ,  4.  ],
       [ 8.  ,  6.3 ,  5.6 ],
       [ 1.2 ,  2.3 ,  4.  ],
       [ 1.25,  2.35,  5.  ],
       [ 1.2 ,  2.4 ,  3.  ],
       [ 8.  ,  6.  ,  5.  ],
       [10.  ,  6.43,  5.61]])

In [5]:
imputer = KNNImputer(n_neighbors=2)
imputer.fit_transform(X)

array([[ 1.  ,  2.  ,  4.5 ],
       [ 8.  ,  6.3 ,  5.6 ],
       [ 1.2 ,  2.3 ,  4.  ],
       [ 1.25,  2.35,  5.  ],
       [ 1.2 ,  2.4 ,  3.  ],
       [ 9.  ,  6.  ,  5.  ],
       [10.  ,  6.43,  5.61]])

In [6]:
imputer = KNNImputer(n_neighbors=3)
imputer.fit_transform(X)

array([[ 1.        ,  2.        ,  4.        ],
       [ 8.        ,  6.3       ,  5.6       ],
       [ 1.2       ,  2.3       ,  4.        ],
       [ 1.25      ,  2.35      ,  5.        ],
       [ 1.2       ,  2.4       ,  3.        ],
       [ 6.41666667,  6.        ,  5.        ],
       [10.        ,  6.43      ,  5.61      ]])